USE CONFERE_TABLET_CPMS

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('PRONTUARIOSCRC'))
	CREATE TABLE PRONTUARIOSCRC
	(
	IdInternoCrc INT IDENTITY (1,1) PRIMARY KEY NOT NULL,	
	Cnc VARCHAR(20) NULL,	
	ImagemFrente VARBINARY(MAX) NULL,
	NomeInternoCrc VARCHAR(150) NOT NULL,	
	Regime VARCHAR(30) NULL,	
	SituacaoCrc VARCHAR(100) NULL,	
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('PAVILHAO'))
	CREATE TABLE PAVILHAO
	(
	IdPav INT PRIMARY KEY(IdPav)NOT NULL,	
	StatusPav VARCHAR(10) NULL,	
	DescricaoPav VARCHAR(150) NOT NULL,
	Motivo VARCHAR(100) NULL,
	PavilhaoCelaBpa VARCHAR(15) NULL,
	NivelPav VARCHAR(1) NULL,	
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('CELAS'))
	CREATE TABLE CELAS
	(
	IdCela INT PRIMARY KEY(IdCela)NOT NULL,	
	StatusCela VARCHAR(10) NULL,
	IdPav INT FOREIGN KEY REFERENCES PAVILHAO(IdPav) NOT NULL,
	EndCelaPav VARCHAR(50) NOT NULL,
	Motivo VARCHAR(100) NULL,
	Capacidade INT NULL,
	NrCela INT NULL,
	NivelCel VARCHAR(1) NULL,	
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('ITENSLOCACAOINTERNO'))
	CREATE TABLE ITENSLOCACAOINTERNO
	(
	IdItem INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	--IdLoca INT FOREIGN KEY REFERENCES LOCACAOINTERNO(IdLoca) NOT NULL,
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	IdCela INT FOREIGN KEY REFERENCES CELAS(IdCela) NOT NULL,
	QtdLanc INT NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)

IF NOT EXISTS (SELECT NULL FROM SYSOBJECTS WHERE ID = OBJECT_ID('CONFERE_INTERNOS'))
	CREATE TABLE CONFERE_INTERNOS
	(
	IdConfere INT IDENTITY(1,1) PRIMARY KEY NOT NULL,	
	IdInternoCrc INT FOREIGN KEY REFERENCES PRONTUARIOSCRC(IdInternoCrc) NOT NULL,
	DataConfere DATETIME NULL,
	DataRealizacao VARCHAR(20) NULL,
	HorarioConfere VARCHAR(20) NULL,
	AssinaturaBiometricaInterno VARBINARY(MAX) NULL,	
	IdPav INT FOREIGN KEY REFERENCES PAVILHAO(IdPav) NOT NULL,
	IdCela INT FOREIGN KEY REFERENCES CELAS(IdCela) NOT NULL,
	UsuarioInsert VARCHAR(50) NULL,
	UsuarioUp VARCHAR(50) NULL,	
	DataInsert VARCHAR(20) NULL,
	DataUp VARCHAR(20) NULL,	
	HorarioInsert VARCHAR(10) NULL,
	HorarioUp VARCHAR(10) NULL,
	)